#!/bin/bash
issued_coin=$(curl -s https://explorer.talleo.org/api/get_generated_coins | jq -r '.alreadyGeneratedCoins')
echo "Content-type: text/plain"
echo ""
awk "BEGIN {printf \"%.8f\n\", $issued_coin/300000000}"
exit 0
